# Generated by Django 4.2.1 on 2023-05-23 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=100, null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=300, null=True)),
                ('icon', models.CharField(blank=True, db_column='Icon', max_length=100, null=True)),
                ('active', models.IntegerField(blank=True, db_column='Active', null=True)),
                ('created_by', models.CharField(blank=True, db_column='Created_by', max_length=100, null=True)),
                ('created_date', models.DateTimeField(blank=True, db_column='Created_date', null=True)),
                ('updated_by', models.CharField(blank=True, db_column='Updated_by', max_length=100, null=True)),
                ('updated_date', models.DateTimeField(blank=True, db_column='Updated_date', null=True)),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=100, null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=300, null=True)),
                ('active', models.IntegerField(blank=True, db_column='Active', null=True)),
                ('created_by', models.CharField(blank=True, db_column='Created_by', max_length=100, null=True)),
                ('created_date', models.DateTimeField(blank=True, db_column='Created_date', null=True)),
                ('updated_by', models.CharField(blank=True, db_column='Updated_by', max_length=100, null=True)),
                ('updated_date', models.DateTimeField(blank=True, db_column='Updated_date', null=True)),
            ],
            options={
                'db_table': 'cities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=100, null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=300, null=True)),
                ('profile', models.CharField(blank=True, db_column='Profile', max_length=100, null=True)),
                ('active', models.IntegerField(blank=True, db_column='Active', null=True)),
                ('created_by', models.CharField(blank=True, db_column='Created_by', max_length=100, null=True)),
                ('created_date', models.DateTimeField(blank=True, db_column='Created_date', null=True)),
                ('updated_by', models.CharField(blank=True, db_column='Updated_by', max_length=100, null=True)),
                ('updated_date', models.DateTimeField(blank=True, db_column='Updated_date', null=True)),
            ],
            options={
                'db_table': 'countries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FilesMst',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('url', models.CharField(blank=True, db_column='Url', max_length=200, null=True)),
                ('active', models.IntegerField(blank=True, db_column='Active', null=True)),
                ('created_by', models.CharField(blank=True, db_column='Created_by', max_length=100, null=True)),
                ('created_date', models.DateTimeField(blank=True, db_column='Created_date', null=True)),
                ('updated_by', models.CharField(blank=True, db_column='Updated_by', max_length=100, null=True)),
                ('updated_date', models.DateTimeField(blank=True, db_column='Updated_date', null=True)),
            ],
            options={
                'db_table': 'files_mst',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=45, null=True)),
                ('sympol', models.CharField(blank=True, db_column='Sympol', max_length=45, null=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=200, null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=400, null=True)),
                ('logo', models.CharField(blank=True, db_column='Logo', max_length=100, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=45, null=True)),
                ('website', models.CharField(blank=True, db_column='Website', max_length=100, null=True)),
                ('direction', models.CharField(blank=True, db_column='Direction', max_length=200, null=True)),
                ('active', models.IntegerField(blank=True, db_column='Active', null=True)),
                ('created_by', models.CharField(blank=True, db_column='Created_by', max_length=100, null=True)),
                ('created_date', models.DateTimeField(blank=True, db_column='Created_date', null=True)),
                ('updated_by', models.CharField(blank=True, db_column='Updated_by', max_length=100, null=True)),
                ('updated_date', models.DateTimeField(blank=True, db_column='Updated_date', null=True)),
            ],
            options={
                'db_table': 'sub_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=100, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=45, null=True)),
                ('username', models.CharField(blank=True, db_column='Username', max_length=45, null=True)),
                ('password', models.CharField(blank=True, db_column='Password', max_length=45, null=True)),
                ('active', models.IntegerField(blank=True, db_column='Active', null=True)),
                ('created_by', models.CharField(blank=True, db_column='Created_by', max_length=100, null=True)),
                ('created_date', models.DateTimeField(blank=True, db_column='Created_date', null=True)),
                ('updated_by', models.CharField(blank=True, db_column='Updated_by', max_length=100, null=True)),
                ('updated_date', models.DateTimeField(blank=True, db_column='Updated_date', null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
